# Generated by Django 2.1.7 on 2019-02-28 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190228_0947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
