# Generated by Django 2.1.7 on 2019-07-21 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
